/**
 * Master Data & Multi-Language i18n Dictionaries
 */

export const LANGUAGES = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "id", name: "Indonesia", flag: "🇮🇩" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "zh-CN", name: "简体中文", flag: "🇨🇳" },
  { code: "zh-HK", name: "繁體中文", flag: "🇭🇰" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "ru", name: "Русский", flag: "🇷🇺" }
];

export const CATEGORIES = [
  { id: "cat-1", num: "01", color: "blue" },
  { id: "cat-2", num: "02", color: "magenta" },
  { id: "cat-3", num: "03", color: "orange" },
  { id: "cat-4", num: "04", color: "cyan" },
  { id: "cat-5", num: "05", color: "green" },
  { id: "cat-6", num: "06", color: "red" },
  { id: "cat-7", num: "07", color: "yellow" }
];

export const I18N = {
  en: {
    heroEyebrow: "Senior Neovim Reference · Tokyo Night Palette",
    heroTitleHtml: 'Lazy<span class="accent">Vim</span> <span class="accent2">Cheatsheet</span>',
    heroSub: "Complete reference for default LazyVim keymaps — from editing, navigation, Neo-tree, Telescope, window management, to Git integration via LazyGit & Gitsigns.",
    leaderDesc: "= Space bar (default LazyVim leader key)",
    searchPlaceholder: "Search shortcuts ('/' or Ctrl+K)...",
    searchStats: "{count} shortcuts found",
    searchStatsSingular: "1 shortcut found",
    searchEmptyTitle: "No shortcuts match your query",
    searchEmptyDesc: "Try searching by key (e.g. <leader>, <C-s>), action name, or mode.",
    colCategory: "Category",
    colAction: "Action / Feature",
    colMode: "Mode",
    colKeymap: "Keymap",
    colDesc: "Description & Function",
    cat7NoteHtml: "<b>Note:</b> <span class=\"k leader\">&lt;leader&gt;w</span> in default LazyVim is the <b>'Windows' group</b> (see Category 05), not Save. Saving defaults to <span class=\"k\">&lt;C-s&gt;</span> or <span class=\"k\">:w</span>.",
    footerHtml: "Crafted for the LazyVim workflow — combine with <span class=\"k\">:Tutor</span> and <span class=\"k leader\">&lt;leader&gt;</span><span class=\"k\">sk</span> to explore all keymaps.",
    categories: {
      "cat-1": { title: "Editing, Selection & Clipboard", desc: "Text manipulation: select, yank/copy, cut, paste, undo/redo, comment, and search-replace." },
      "cat-2": { title: "Quick Cursor Navigation", desc: "Move inside files without touching the mouse, jump to definitions via LSP." },
      "cat-3": { title: "File Explorer (Neo-tree) & Project", desc: "Sidebar file management with Neo-tree: create, delete, rename, and switch projects." },
      "cat-4": { title: "Fuzzy Finder (Telescope / fzf-lua)", desc: "Find files, text, buffers, and symbols — the search-and-jump heart of LazyVim." },
      "cat-5": { title: "Buffer, Window & Split Management", desc: "Manage multiple open files and window splits without losing context." },
      "cat-6": { title: "Git Integration (LazyGit & Gitsigns)", desc: "Version control in editor: full LazyGit UI and inline hunk changes via Gitsigns." },
      "cat-7": { title: "System, Save & Exit", desc: "Core system commands: save, quit, plugin manager, and Neovim health check." }
    }
  },
  id: {
    heroEyebrow: "Senior Neovim Reference · Tokyonight Palette",
    heroTitleHtml: 'Lazy<span class="accent">Vim</span> <span class="accent2">Cheatsheet</span>',
    heroSub: "Referensi lengkap keymap bawaan LazyVim — dari editing, navigasi, Neo-tree, Telescope, window management, sampai integrasi Git via LazyGit & Gitsigns. Cetak, simpan sebagai PDF, atau tempel di monitor kedua.",
    leaderDesc: "= tombol Spasi (Space) — default LazyVim",
    searchPlaceholder: "Cari keymap ('/' atau Ctrl+K)...",
    searchStats: "Ditemukan {count} keymap yang cocok",
    searchStatsSingular: "Ditemukan 1 keymap yang cocok",
    searchEmptyTitle: "Tidak ada keymap yang sesuai",
    searchEmptyDesc: "Coba cari berdasarkan tombol (mis. <leader>, <C-s>), nama aksi, atau mode.",
    colCategory: "Kategori",
    colAction: "Aksi / Fitur",
    colMode: "Mode",
    colKeymap: "Keymap",
    colDesc: "Deskripsi & Fungsi",
    cat7NoteHtml: "<b>Catatan:</b> <span class=\"k leader\">&lt;leader&gt;w</span> pada LazyVim default adalah <b>grup 'Windows'</b> (lihat Kategori 05), bukan shortcut Save — sehingga Save menggunakan <span class=\"k\">&lt;C-s&gt;</span> atau <span class=\"k\">:w</span> secara default.",
    footerHtml: "Dibuat untuk workflow LazyVim — kombinasikan dengan <span class=\"k\">:Tutor</span> dan <span class=\"k leader\">&lt;leader&gt;</span><span class=\"k\">sk</span> untuk eksplorasi keymap lebih lanjut.",
    categories: {
      "cat-1": { title: "Editing, Selection & Clipboard", desc: "Manipulasi teks: select, yank/copy, cut, paste, undo/redo, comment, dan search-replace." },
      "cat-2": { title: "Navigasi Kursor Cepat", desc: "Berpindah posisi dalam file tanpa menyentuh mouse, sampai lompat ke definisi kode via LSP." },
      "cat-3": { title: "File Explorer (Neo-tree) & Project", desc: "Sidebar manajemen file berbasis Neo-tree — buat, hapus, rename, sampai pindah antar project." },
      "cat-4": { title: "Pencarian & Navigasi File (Telescope / fzf-lua)", desc: "Fuzzy finder untuk file, teks, buffer, dan lainnya — jantung workflow 'cari-lalu-lompat' di LazyVim." },
      "cat-5": { title: "Buffer, Window & Split Management", desc: "Mengatur banyak file terbuka sekaligus dalam satu layar tanpa kehilangan konteks." },
      "cat-6": { title: "Integrasi Git (LazyGit & Gitsigns)", desc: "Version control tanpa keluar dari editor — UI penuh via LazyGit dan indikator perubahan baris via Gitsigns." },
      "cat-7": { title: "System, Save & Exit", desc: "Perintah dasar sistem: simpan, keluar, dan manajemen plugin/LSP." }
    }
  },
  es: {
    heroEyebrow: "Referencia Neovim Senior · Paleta Tokyo Night",
    heroTitleHtml: 'Lazy<span class="accent">Vim</span> <span class="accent2">Cheatsheet</span>',
    heroSub: "Referencia completa de atajos de LazyVim: edición, navegación, Neo-tree, Telescope, ventanas e integración con Git.",
    leaderDesc: "= Tecla Espacio (líder predeterminado en LazyVim)",
    searchPlaceholder: "Buscar atajos ('/' o Ctrl+K)...",
    searchStats: "{count} atajos encontrados",
    searchStatsSingular: "1 atajo encontrado",
    searchEmptyTitle: "No se encontraron atajos",
    searchEmptyDesc: "Prueba buscando por tecla (<leader>, <C-s>), acción o modo.",
    colCategory: "Categoría",
    colAction: "Acción / Función",
    colMode: "Modo",
    colKeymap: "Atajo",
    colDesc: "Descripción y Función",
    cat7NoteHtml: "<b>Nota:</b> <span class=\"k leader\">&lt;leader&gt;w</span> en LazyVim pertenece al <b>grupo 'Ventanas'</b> (ver Categoría 05), no a Guardar. Guardar utiliza <span class=\"k\">&lt;C-s&gt;</span> o <span class=\"k\">:w</span>.",
    footerHtml: "Creado para el flujo de trabajo LazyVim — combina con <span class=\"k\">:Tutor</span> y <span class=\"k leader\">&lt;leader&gt;</span><span class=\"k\">sk</span> para explorar más atajos.",
    categories: {
      "cat-1": { title: "Edición, Selección y Portapapeles", desc: "Manipulación de texto: copiar, cortar, pegar, deshacer, comentarios y reemplazar." },
      "cat-2": { title: "Navegación Rápida del Cursor", desc: "Desplázate sin ratón y salta directamente a definiciones mediante LSP." },
      "cat-3": { title: "Explorador de Archivos (Neo-tree) y Proyectos", desc: "Gestión lateral con Neo-tree: crear, eliminar, renombrar y alternar proyectos." },
      "cat-4": { title: "Buscador Difuso (Telescope / fzf-lua)", desc: "Búsqueda difusa para archivos, texto en vivo, buffers y símbolos del proyecto." },
      "cat-5": { title: "Gestión de Buffers y Ventanas Divididas", desc: "Organiza múltiples archivos abiertos y divisiones de ventana sin perder contexto." },
      "cat-6": { title: "Integración Git (LazyGit y Gitsigns)", desc: "Control de versiones en el editor: interfaz LazyGit y cambios de hunk con Gitsigns." },
      "cat-7": { title: "Sistema, Guardar y Salir", desc: "Comandos principales: guardar, salir, gestor de plugins lazy.nvim y diagnóstico." }
    }
  },
  de: {
    heroEyebrow: "Senior Neovim Referenz · Tokyo Night Palette",
    heroTitleHtml: 'Lazy<span class="accent">Vim</span> <span class="accent2">Cheatsheet</span>',
    heroSub: "Vollständige Referenz für Standard-LazyVim-Tastenkürzel – von Bearbeitung, Navigation, Neo-tree, Telescope bis zu Git-Integration.",
    leaderDesc: "= Leertaste (Standard-Leader-Taste in LazyVim)",
    searchPlaceholder: "Tastenkürzel suchen ('/' oder Strg+K)...",
    searchStats: "{count} Tastenkürzel gefunden",
    searchStatsSingular: "1 Tastenkürzel gefunden",
    searchEmptyTitle: "Keine Tastenkürzel gefunden",
    searchEmptyDesc: "Suche nach Tasten (<leader>, <C-s>), Aktionsnamen oder Modi.",
    colCategory: "Kategorie",
    colAction: "Aktion / Feature",
    colMode: "Modus",
    colKeymap: "Tastenkürzel",
    colDesc: "Beschreibung & Funktion",
    cat7NoteHtml: "<b>Hinweis:</b> <span class=\"k leader\">&lt;leader&gt;w</span> ist in LazyVim standardmäßig die <b>'Windows'-Gruppe</b> (siehe Kat 05). Speichern erfolgt über <span class=\"k\">&lt;C-s&gt;</span> oder <span class=\"k\">:w</span>.",
    footerHtml: "Erstellt für den LazyVim-Workflow — kombiniere mit <span class=\"k\">:Tutor</span> und <span class=\"k leader\">&lt;leader&gt;</span><span class=\"k\">sk</span> für weitere Keymaps.",
    categories: {
      "cat-1": { title: "Bearbeitung, Auswahl & Zwischenablage", desc: "Textmanipulation: Auswählen, Kopieren, Einfügen, Undo/Redo, Kommentare und Suchen/Ersetzen." },
      "cat-2": { title: "Schnelle Cursornavigation", desc: "Navigation im Code ohne Maus, Definitionen und Referenzen via LSP anspringen." },
      "cat-3": { title: "Dateimanager (Neo-tree) & Projekte", desc: "Sidebar-Dateiverwaltung mit Neo-tree: Erstellen, Löschen, Umbenennen und Projektwechsel." },
      "cat-4": { title: "Fuzzy Finder (Telescope / fzf-lua)", desc: "Dateien, Live-Grep, Puffer und Symbole blitzschnell durchsuchen." },
      "cat-5": { title: "Puffer-, Fenster- & Split-Verwaltung", desc: "Mehrere Dateien und geteilte Ansichten flexibel organisieren." },
      "cat-6": { title: "Git-Integration (LazyGit & Gitsigns)", desc: "Versionskontrolle im Editor: Vollwertiges LazyGit-Terminal und Hunk-Diffs via Gitsigns." },
      "cat-7": { title: "System, Speichern & Beenden", desc: "Grundlegende Befehle: Speichern, Beenden, lazy.nvim Plugin-Manager und Systemcheck." }
    }
  },
  "zh-CN": {
    heroEyebrow: "资深 Neovim 参考手册 · Tokyo Night 配色",
    heroTitleHtml: 'Lazy<span class="accent">Vim</span> <span class="accent2">快捷键速查表</span>',
    heroSub: "LazyVim 默认键位映射完整参考手册 —— 涵盖文本编辑、光标移动、Neo-tree 文件树、Telescope 搜索、窗口分屏及 Git 深度集成。",
    leaderDesc: "= 空格键 (Space) — LazyVim 默认 Leader 键",
    searchPlaceholder: "搜索快捷键 (按 '/' 或 Ctrl+K)...",
    searchStats: "找到 {count} 个快捷键",
    searchStatsSingular: "找到 1 个快捷键",
    searchEmptyTitle: "未找到匹配的快捷键",
    searchEmptyDesc: "尝试按按键 (如 <leader>, <C-s>)、操作名称或编辑模式搜索。",
    colCategory: "分类",
    colAction: "操作 / 功能",
    colMode: "模式",
    colKeymap: "键位映射",
    colDesc: "详细说明与功能",
    cat7NoteHtml: "<b>注意：</b> LazyVim 中 <span class=\"k leader\">&lt;leader&gt;w</span> 默认对应 <b>'Windows' 窗口分组</b>（见分类 05），而非保存文件。默认保存请使用 <span class=\"k\">&lt;C-s&gt;</span> 或 <span class=\"k\">:w</span>。",
    footerHtml: "专为 LazyVim 工作流设计 —— 结合 <span class=\"k\">:Tutor</span> 与 <span class=\"k leader\">&lt;leader&gt;</span><span class=\"k\">sk</span> 探索全部快捷键。",
    categories: {
      "cat-1": { title: "文本编辑、选择与剪贴板", desc: "文本操作：选中、复制 (Yank)、剪切、粘贴、撤销/重做、代码注释与查找替换。" },
      "cat-2": { title: "光标高速导航与跳转", desc: "无需触碰鼠标即可在文件中极速穿梭，并通过 LSP 一键跳转至代码定义与引用。" },
      "cat-3": { title: "文件树 (Neo-tree) 与项目管理", desc: "Neo-tree 侧边栏：文件新建、删除、重命名、移动及项目工作区切换。" },
      "cat-4": { title: "模糊查找 (Telescope / fzf-lua)", desc: "全局文件查找、实时文本 Grep、打开的缓冲区以及命令列表检索。" },
      "cat-5": { title: "缓冲区与多窗口分屏管理", desc: "高效管理多个打开的文件、横向/纵向分屏切换、尺寸调整与关闭。" },
      "cat-6": { title: "Git 集成 (LazyGit & Gitsigns)", desc: "编辑器内版本控制：LazyGit 终端弹窗、代码块暂存与行级别 Git Blame。" },
      "cat-7": { title: "系统控制、保存与退出", desc: "核心命令：文件持久化保存、安全退出、Lazy 插件管理与健康诊断。" }
    }
  },
  "zh-HK": {
    heroEyebrow: "資深 Neovim 參考手冊 · Tokyo Night 配色",
    heroTitleHtml: 'Lazy<span class="accent">Vim</span> <span class="accent2">快捷鍵速查表</span>',
    heroSub: "LazyVim 預設鍵位映射完整參考手冊 —— 涵蓋文本編輯、游標移動、Neo-tree 檔案樹、Telescope 搜尋、視窗分屏及 Git 深度整合。",
    leaderDesc: "= 空白鍵 (Space) — LazyVim 預設 Leader 鍵",
    searchPlaceholder: "搜尋快捷鍵 (按 '/' 或 Ctrl+K)...",
    searchStats: "找到 {count} 個快捷鍵",
    searchStatsSingular: "找到 1 個快捷鍵",
    searchEmptyTitle: "找不到相符的快捷鍵",
    searchEmptyDesc: "嘗試按按鍵 (如 <leader>, <C-s>)、操作名稱或編輯模式搜尋。",
    colCategory: "分類",
    colAction: "操作 / 功能",
    colMode: "模式",
    colKeymap: "鍵位映射",
    colDesc: "詳細說明與功能",
    cat7NoteHtml: "<b>注意：</b> LazyVim 中 <span class=\"k leader\">&lt;leader&gt;w</span> 預設對應 <b>'Windows' 視窗分組</b>（見分類 05），而非儲存檔案。預設儲存請使用 <span class=\"k\">&lt;C-s&gt;</span> 或 <span class=\"k\">:w</span>。",
    footerHtml: "專為 LazyVim 工作流程打造 —— 結合 <span class=\"k\">:Tutor</span> 與 <span class=\"k leader\">&lt;leader&gt;</span><span class=\"k\">sk</span> 探索全部快捷鍵。",
    categories: {
      "cat-1": { title: "文本編輯、選取與剪貼簿", desc: "文本操作：選取、複製 (Yank)、剪下、貼上、復原/重做、程式碼註解與取代。" },
      "cat-2": { title: "游標快速導航與跳轉", desc: "無須觸碰滑鼠即可在檔案中極速穿梭，並透過 LSP 一鍵跳轉至程式碼定義與引用。" },
      "cat-3": { title: "檔案樹 (Neo-tree) 與專案管理", desc: "Neo-tree 側邊欄：檔案新建、刪除、重新命名、移動及專案工作區切換。" },
      "cat-4": { title: "模糊搜尋 (Telescope / fzf-lua)", desc: "全局檔案搜尋、即時文本 Grep、開啟的緩衝區及指令列表檢索。" },
      "cat-5": { title: "緩衝區與多視窗分屏管理", desc: "高效管理多個開啟的檔案、橫向/縱向分屏切換、尺寸調整與關閉。" },
      "cat-6": { title: "Git 整合 (LazyGit & Gitsigns)", desc: "編輯器內版本控制：LazyGit 終端彈窗、程式碼塊暫存與行級別 Git Blame。" },
      "cat-7": { title: "系統控制、儲存與結束", desc: "核心指令：檔案持久化儲存、安全退出、Lazy 套件管理與健康診斷。" }
    }
  },
  ja: {
    heroEyebrow: "上級 Neovim リファレンス · Tokyo Night パレット",
    heroTitleHtml: 'Lazy<span class="accent">Vim</span> <span class="accent2">チートシート</span>',
    heroSub: "LazyVim デフォルトキーマップの完全リファレンス — 編集、ナビゲーション、Neo-tree、Telescope、ウィンドウ分割、LazyGit 連携まで網羅。",
    leaderDesc: "= スペースキー (Space) — LazyVim デフォルト Leader",
    searchPlaceholder: "ショートカットを検索 ('/' または Ctrl+K)...",
    searchStats: "{count} 件のショートカットが見つかりました",
    searchStatsSingular: "1 件のショートカットが見つかりました",
    searchEmptyTitle: "一致するショートカットがありません",
    searchEmptyDesc: "キー (<leader>, <C-s>)、操作名、またはモードで検索してください。",
    colCategory: "カテゴリ",
    colAction: "操作 / 機能",
    colMode: "モード",
    colKeymap: "キーマップ",
    colDesc: "説明と詳細機能",
    cat7NoteHtml: "<b>注記:</b> LazyVim の <span class=\"k leader\">&lt;leader&gt;w</span> はデフォルトで <b>'Windows' グループ</b> です。保存は <span class=\"k\">&lt;C-s&gt;</span> または <span class=\"k\">:w</span> を使用します。",
    footerHtml: "LazyVim ワークフロー向けに最適化 — <span class=\"k\">:Tutor</span> および <span class=\"k leader\">&lt;leader&gt;</span><span class=\"k\">sk</span> と組み合わせて探索してください。",
    categories: {
      "cat-1": { title: "編集・選択・クリップボード", desc: "テキスト操作: 選択、ヤンク/コピー、カット、ペースト、Undo/Redo、コメント化、置換。" },
      "cat-2": { title: "高速カーソルナビゲーション", desc: "マウス不要のファイル内移動、LSP による定義・参照への高速ジャンプ。" },
      "cat-3": { title: "ファイルエクスプローラ (Neo-tree) & プロジェクト", desc: "Neo-tree サイドバー管理: ファイル作成、削除、リネーム、プロジェクト切り替え。" },
      "cat-4": { title: "ファジーファインダー (Telescope / fzf-lua)", desc: "ファイル検索、リアルタイム Grep、バッファ一覧、キーマップ検索。" },
      "cat-5": { title: "バッファ・ウィンドウ・画面分割", desc: "開いているバッファや垂直/水平分割ウィンドウを快適にコントロール。" },
      "cat-6": { title: "Git 統合 (LazyGit & Gitsigns)", desc: "エディタ内バージョン管理: LazyGit ターミナル UI、ハンク操作、行単位の Blame。" },
      "cat-7": { title: "システム制御・保存・終了", desc: "基本コマンド: 保存、安全な終了、lazy.nvim プラグイン管理、ヘルスチェック。" }
    }
  },
  ko: {
    heroEyebrow: "시니어 Neovim 레퍼런스 · Tokyo Night 팔레트",
    heroTitleHtml: 'Lazy<span class="accent">Vim</span> <span class="accent2">치트시트</span>',
    heroSub: "LazyVim 기본 단축키 완벽 레퍼런스 — 편집, 내비게이션, Neo-tree, Telescope, 창 분할, Git 연동까지 완벽 정리.",
    leaderDesc: "= 스페이스 바 (Space) — LazyVim 기본 리더 키",
    searchPlaceholder: "단축키 검색 ('/' 또는 Ctrl+K 입력)...",
    searchStats: "{count}개의 단축키를 찾았습니다",
    searchStatsSingular: "1개의 단축키를 찾았습니다",
    searchEmptyTitle: "일치하는 단축키가 없습니다",
    searchEmptyDesc: "키 조합(<leader>, <C-s>), 기능 이름 또는 모드로 검색해 보세요.",
    colCategory: "카테고리",
    colAction: "기능 / 동작",
    colMode: "모드",
    colKeymap: "단축키",
    colDesc: "설명 및 세부 기능",
    cat7NoteHtml: "<b>참고:</b> LazyVim에서 <span class=\"k leader\">&lt;leader&gt;w</span>는 기본적으로 <b>'Windows' 그룹</b>입니다. 저장은 <span class=\"k\">&lt;C-s&gt;</span> 또는 <span class=\"k\">:w</span>를 사용합니다.",
    footerHtml: "LazyVim 워크플로를 위해 제작됨 — <span class=\"k\">:Tutor</span> 및 <span class=\"k leader\">&lt;leader&gt;</span><span class=\"k\">sk</span> 명령어로 탐색하세요.",
    categories: {
      "cat-1": { title: "편집, 선택 및 클립보드", desc: "텍스트 조작: 전체 선택, 복사(Yank), 잘라내기, 붙여넣기, 실행 취소/다시 실행, 주석 및 찾기/바꾸기。" },
      "cat-2": { title: "빠른 커서 내비게이션", desc: "마우스 없는 빠른 이동 및 LSP 기반 심볼 정의/참조 바로가기." },
      "cat-3": { title: "파일 탐색기 (Neo-tree) 및 프로젝트", desc: "Neo-tree 사이드바 관리: 파일 생성, 삭제, 이름 변경 및 프로젝트 전환." },
      "cat-4": { title: "퍼지 검색 (Telescope / fzf-lua)", desc: "파일, 텍스트 실시간 검색(Live Grep), 열린 버퍼 및 단축키 목록 검색." },
      "cat-5": { title: "버퍼, 창 및 분할 화면 관리", desc: "다중 파일 관리, 세로/가로 분할 창 이동, 크기 조절 및 안전한 버퍼 닫기." },
      "cat-6": { title: "Git 연동 (LazyGit 및 Gitsigns)", desc: "에디터 내 버전 관리: 전체 LazyGit 터미널 UI, 헝크 스테이징 및 Git Blame 확인." },
      "cat-7": { title: "시스템, 저장 및 종료", desc: "핵심 시스템 명령: 파일 저장, 종료, lazy.nvim 플러그인 관리, Mason 및 상태 진단." }
    }
  },
  ru: {
    heroEyebrow: "Справочник Neovim · Палитра Tokyo Night",
    heroTitleHtml: 'Lazy<span class="accent">Vim</span> <span class="accent2">Шпаргалка</span>',
    heroSub: "Полный справочник горячих клавиш LazyVim по умолчанию: редактирование, навигация, Neo-tree, Telescope, сплиты и Git.",
    leaderDesc: "= Клавиша Пробел (Space) — по умолчанию в LazyVim",
    searchPlaceholder: "Поиск клавиш ('/' или Ctrl+K)...",
    searchStats: "Найдено горячих клавиш: {count}",
    searchStatsSingular: "Найдена 1 горячая клавиша",
    searchEmptyTitle: "Сочетания не найдены",
    searchEmptyDesc: "Попробуйте поиск по клавишам (<leader>, <C-s>), действию или режиму.",
    colCategory: "Категория",
    colAction: "Действие / Функция",
    colMode: "Режим",
    colKeymap: "Клавиши",
    colDesc: "Описание и функции",
    cat7NoteHtml: "<b>Примечание:</b> <span class=\"k leader\">&lt;leader&gt;w</span> в LazyVim по умолчанию — группа <b>'Окна'</b>. Для сохранения используйте <span class=\"k\">&lt;C-s&gt;</span> или <span class=\"k\">:w</span>.",
    footerHtml: "Создано для LazyVim — используйте <span class=\"k\">:Tutor</span> и <span class=\"k leader\">&lt;leader&gt;</span><span class=\"k\">sk</span> для изучения всех клавиш.",
    categories: {
      "cat-1": { title: "Редактирование, Выделение и Буфер", desc: "Манипуляции с текстом: выделение, копирование (yank), вырезание, вставка, отмена/повтор, комментарии и замена." },
      "cat-2": { title: "Быстрая Навигация Курсора", desc: "Перемещение по файлу без мыши и мгновенный переход к определениям и ссылкам через LSP." },
      "cat-3": { title: "Проводник (Neo-tree) и Проекты", desc: "Боковая панель файлов Neo-tree: создание, удаление, переименование и переключение проектов." },
      "cat-4": { title: "Fuzzy-поиск (Telescope / fzf-lua)", desc: "Мгновенный поиск файлов, поиск текста по проекту (Live Grep), буферы и справка." },
      "cat-5": { title: "Буферы, Окна и Сплиты", desc: "Управление несколькими открытыми файлами, вертикальные/горизонтальные сплиты и изменение размера." },
      "cat-6": { title: "Интеграция с Git (LazyGit и Gitsigns)", desc: "Контроль версий в редакторе: полный интерфейс LazyGit, работа с ханками и построчный Git Blame." },
      "cat-7": { title: "Система, Сохранение и Выход", desc: "Базовые команды: сохранение, выход, менеджер плагинов lazy.nvim, Mason и проверка здоровья." }
    }
  }
};

const RAW_KEYMAP_DATA = [
  /* Category 1 */
  ["c1_01","cat-1","Normal",'<span class="k">gg</span><span class="k">V</span><span class="k">G</span>',"ggVG gg V G",
    {en:"Select All",id:"Pilih Semua",es:"Seleccionar todo",de:"Alles auswählen","zh-CN":"全选","zh-HK":"全選",ja:"すべて選択",ko:"전체 선택",ru:"Выделить всё"},
    {en:"Select entire file contents from first to last line.",id:"Pilih seluruh isi file dari baris pertama sampai terakhir."}],
  ["c1_02","cat-1","Normal",'<span class="k">yy</span>',"yy",
    {en:"Yank line",id:"Yank baris",es:"Copiar línea",de:"Zeile kopieren","zh-CN":"复制整行","zh-HK":"複製整行",ja:"行をヤンク",ko:"한 줄 복사",ru:"Копировать строку"},
    {en:"Copy entire line into the default (unnamed) register.",id:"Copy satu baris penuh ke register default (unnamed)."}],
  ["c1_03","cat-1","Visual",'<span class="k">y</span>',"y",
    {en:"Yank selection",id:"Yank selection",es:"Copiar selección",de:"Auswahl kopieren","zh-CN":"复制选中内容","zh-HK":"複製選取內容",ja:"選択範囲をヤンク",ko:"선택 영역 복사",ru:"Копировать выделение"},
    {en:"Copy active visual selection into register.",id:"Copy teks yang sedang diseleksi ke register."}],
  ["c1_04","cat-1","Normal / Visual",'<span class="k">"+y</span>','"+y "+',
    {en:"Yank to system clipboard",id:"Yank ke system clipboard",es:"Copiar al portapapeles del sistema",de:"In System-Zwischenablage kopieren","zh-CN":"复制到系统剪贴板","zh-HK":"複製至系統剪貼簿",ja:"システムクリップボードへヤンク",ko:"시스템 클립보드로 복사",ru:"Копировать в системный буфер"},
    {en:"Copy directly to OS system clipboard (+ register).",id:"Copy ke clipboard sistem OS (perlu xclip/wl-clipboard atau clipboard=unnamedplus aktif)."}],
  ["c1_05","cat-1","Normal",'<span class="k">yw</span>',"yw",
    {en:"Yank word",id:"Yank per kata",es:"Copiar palabra",de:"Wort kopieren","zh-CN":"复制单词","zh-HK":"複製單詞",ja:"単語をヤンク",ko:"단어 복사",ru:"Копировать слово"},
    {en:"Yank from cursor position to end of word.",id:"Yank dari posisi kursor sampai akhir kata berikutnya."}],
  ["c1_06","cat-1","Normal",'<span class="k">x</span>',"x",
    {en:"Cut character",id:"Cut karakter",es:"Cortar carácter",de:"Zeichen ausschneiden","zh-CN":"剪切字符",ja:"1文字切り取り",ko:"문자 잘라내기",ru:"Вырезать символ"},
    {en:"Delete single character under cursor and save to register.",id:"Hapus 1 karakter di bawah kursor, tersimpan di register."}],
  ["c1_07","cat-1","Normal",'<span class="k">dd</span>',"dd",
    {en:"Cut / Delete line",id:"Cut / Delete baris",es:"Cortar / Eliminar línea",de:"Zeile ausschneiden / löschen","zh-CN":"剪切/删除整行",ja:"行を切り取り/削除",ko:"한 줄 잘라내기/삭제",ru:"Вырезать / удалить строку"},
    {en:"Delete entire line and cut it into unnamed register.",id:"Hapus satu baris penuh sekaligus meng-cut ke register default."}],
  ["c1_08","cat-1","Normal",'<span class="k">dw</span>',"dw",
    {en:"Cut word",id:"Cut per kata",es:"Cortar palabra",de:"Wort ausschneiden","zh-CN":"剪切单词",ja:"単語を切り取り",ko:"단어 잘라내기",ru:"Вырезать слово"},
    {en:"Delete from cursor to start of next word.",id:"Hapus dari kursor sampai awal kata berikutnya."}],
  ["c1_09","cat-1","Normal",'<span class="k">D</span>',"D d$",
    {en:"Cut to end of line",id:"Cut sampai akhir baris",es:"Cortar hasta fin de línea",de:"Bis Zeilenende ausschneiden","zh-CN":"剪切至行尾",ja:"行末まで切り取り",ko:"줄 끝까지 잘라내기",ru:"Вырезать до конца строки"},
    {en:"Delete from cursor to line end (equivalent to d$).",id:"Hapus dari posisi kursor sampai akhir baris (setara d$)."}],
  ["c1_10","cat-1","Visual",'<span class="k">d</span>',"d",
    {en:"Delete selection",id:"Delete selection",es:"Eliminar selección",de:"Auswahl löschen","zh-CN":"删除选中内容",ja:"選択範囲を削除",ko:"선택 영역 삭제",ru:"Удалить выделение"},
    {en:"Delete active visual selection and save to register.",id:"Hapus teks yang diseleksi, tersimpan di register."}],
  ["c1_11","cat-1","Normal",'<span class="k">p</span>',"p",
    {en:"Paste after cursor",id:"Paste setelah kursor",es:"Pegar después del cursor",de:"Nach Cursor einfügen","zh-CN":"光标后粘贴",ja:"カーソル後に貼り付け",ko:"커서 뒤에 붙여넣기",ru:"Вставить после курсора"},
    {en:"Paste register content after cursor or below current line.",id:"Tempel isi register setelah kursor / di bawah baris aktif."}],
  ["c1_12","cat-1","Normal",'<span class="k">P</span>',"P",
    {en:"Paste before cursor",id:"Paste sebelum kursor",es:"Pegar antes del cursor",de:"Vor Cursor einfügen","zh-CN":"光标前粘贴",ja:"カーソル前に貼り付け",ko:"커서 앞에 붙여넣기",ru:"Вставить перед курсором"},
    {en:"Paste register content before cursor or above current line.",id:"Tempel isi register sebelum kursor / di atas baris aktif."}],
  ["c1_13","cat-1","Normal / Insert",'<span class="k">"+p</span> · <span class="k">&lt;C-r&gt;+</span>','+p <C-r>+ ctrl-r',
    {en:"Paste from system clipboard",id:"Paste dari system clipboard",es:"Pegar del portapapeles del sistema",de:"Aus System-Zwischenablage einfügen","zh-CN":"从系统剪贴板粘贴",ja:"システムクリップボードから貼り付け",ko:"시스템 클립보드에서 붙여넣기",ru:"Вставить из системного буфера"},
    {en:"Paste from OS clipboard; in Insert mode use <C-r>+.",id:"Tempel dari clipboard sistem OS, di Insert mode gunakan <C-r>+."}],
  ["c1_14","cat-1","Visual",'<span class="k">p</span>',"p",
    {en:"Paste without overriding register",id:"Paste tanpa timpa register",es:"Pegar sin sobrescribir registro",de:"Einfügen ohne Register überschreiben","zh-CN":"粘贴且保留剪贴板内容",ja:"レジスタを上書きせず貼り付け",ko:"레지스터 덮어쓰기 없이 붙여넣기",ru:"Вставка без перезаписи регистра"},
    {en:"Paste over selection without losing original register contents.",id:"Tempel menimpa selection tanpa kehilangan isi register."}],
  ["c1_15","cat-1","Normal",'<span class="k">u</span>',"u undo",
    {en:"Undo",id:"Undo",es:"Deshacer",de:"Rückgängig","zh-CN":"撤销",ja:"元に戻す (Undo)",ko:"실행 취소 (Undo)",ru:"Отменить (Undo)"},
    {en:"Undo the last recorded text change.",id:"Batalkan perubahan terakhir."}],
  ["c1_16","cat-1","Normal",'<span class="k">&lt;C-r&gt;</span>',"<C-r> ctrl-r redo",
    {en:"Redo",id:"Redo",es:"Rehacer",de:"Wiederholen","zh-CN":"重做",ja:"やり直し (Redo)",ko:"다시 실행 (Redo)",ru:"Повторить (Redo)"},
    {en:"Redo changes previously reverted by undo.",id:"Ulangi kembali perubahan yang di-undo."}],
  ["c1_17","cat-1","Normal / Visual",'<span class="k">&lt;A-j&gt;</span>',"<A-j> alt-j move down",
    {en:"Move line down",id:"Move line ke bawah",es:"Mover línea hacia abajo",de:"Zeile nach unten verschieben","zh-CN":"向下移动行",ja:"行を下へ移動",ko:"한 줄 아래로 이동",ru:"Сдвинуть строку вниз"},
    {en:"Move active line or visual selection down by one line.",id:"Pindahkan baris aktif (atau seluruh selection) satu baris ke bawah."}],
  ["c1_18","cat-1","Normal / Visual",'<span class="k">&lt;A-k&gt;</span>',"<A-k> alt-k move up",
    {en:"Move line up",id:"Move line ke atas",es:"Mover línea hacia arriba",de:"Zeile nach oben verschieben","zh-CN":"向上移动行",ja:"行を上へ移動",ko:"한 줄 위로 이동",ru:"Сдвинуть строку вверх"},
    {en:"Move active line or visual selection up by one line.",id:"Pindahkan baris aktif (atau seluruh selection) satu baris ke atas."}],
  ["c1_19","cat-1","Normal",'<span class="k">yy</span><span class="plus">→</span><span class="k">p</span>',"yy p yyp duplicate",
    {en:"Duplicate line",id:"Duplicate baris",es:"Duplicar línea",de:"Zeile duplizieren","zh-CN":"复制并粘贴行",ja:"行を複製",ko:"한 줄 복제",ru:"Дублировать строку"},
    {en:"Yank line then immediately paste below to duplicate.",id:"Yank baris lalu paste di bawahnya untuk menduplikasi baris."}],
  ["c1_20","cat-1","Visual",'<span class="k">y</span><span class="plus">→</span><span class="k">gv</span><span class="plus">→</span><span class="k">p</span>',"y gv p ygvp duplicate",
    {en:"Duplicate selection",id:"Duplicate selection",es:"Duplicar selección",de:"Auswahl duplizieren","zh-CN":"复制并粘贴选区",ja:"選択範囲を複製",ko:"선택 영역 복제",ru:"Дублировать выделение"},
    {en:"Yank block, re-select with gv, and paste to duplicate.",id:"Yank blok terpilih, reselect dengan gv, lalu paste untuk menduplikasi blok."}],
  ["c1_21","cat-1","Normal",'<span class="k">gcc</span>',"gcc comment",
    {en:"Toggle comment line",id:"Toggle Comment baris",es:"Comentar/descomentar línea",de:"Zeilenkommentar umschalten","zh-CN":"切换行注释",ja:"行コメントの切り替え",ko:"한 줄 주석 토글",ru:"Переключить комментирование строки"},
    {en:"Comment or uncomment active line according to filetype.",id:"Comment / uncomment baris aktif sesuai filetype."}],
  ["c1_22","cat-1","Visual",'<span class="k">gc</span>',"gc comment",
    {en:"Toggle comment block",id:"Toggle Comment blok",es:"Comentar/descomentar bloque",de:"Blockkommentar umschalten","zh-CN":"切换块注释",ja:"ブロックコメントの切り替え",ko:"블록 주석 토글",ru:"Переключить комментирование блока"},
    {en:"Comment or uncomment selected visual lines.",id:"Comment / uncomment seluruh baris dalam selection."}],
  ["c1_23","cat-1","Normal",'<span class="k">gco</span>',"gco comment",
    {en:"Comment new line below",id:"Comment baris baru di bawah",es:"Comentar nueva línea abajo",de:"Kommentarzeile darunter einfügen","zh-CN":"下方新建注释行",ja:"下行にコメントを挿入",ko:"아래에 새 주석 줄 추가",ru:"Комментировать строку ниже"},
    {en:"Add a new comment line below current line and enter Insert mode.",id:"Buat baris comment baru di bawah baris aktif lalu masuk Insert mode."}],
  ["c1_24","cat-1","Normal",'<span class="k">gcO</span>',"gcO comment",
    {en:"Comment new line above",id:"Comment baris baru di atas",es:"Comentar nueva línea arriba",de:"Kommentarzeile darüber einfügen","zh-CN":"上方新建注释行",ja:"上行にコメントを挿入",ko:"위에 새 주석 줄 추가",ru:"Комментировать строку выше"},
    {en:"Add a new comment line above current line and enter Insert mode.",id:"Buat baris comment baru di atas baris aktif lalu masuk Insert mode."}],
  ["c1_25","cat-1","Normal",'<span class="k">&lt;C-v&gt;</span>',"<C-v> ctrl-v visual block column",
    {en:"Visual Block / Column select",id:"Visual Block / Column select",es:"Bloque visual / Selección de columna",de:"Visueller Block / Spaltenauswahl","zh-CN":"列块选择模式",ja:"ビジュアルブロック選択",ko:"열 블록 선택",ru:"Визуальный блок"},
    {en:"Enter Visual Block mode for vertical column editing.",id:"Masuk mode Visual Block untuk seleksi kolom vertikal."}],
  ["c1_26","cat-1","Command",'<span class="k">:%s/old/new/g</span>',":%s/old/new/g replace substitute",
    {en:"Search & Replace (global)",id:"Search & Replace (global)",es:"Buscar y Reemplazar (global)",de:"Suchen & Ersetzen (global)","zh-CN":"全局查找并替换",ja:"全検索置換 (グローバル)",ko:"전체 찾기 및 바꾸기",ru:"Поиск и замена (глобально)"},
    {en:"Substitute all occurrences of 'old' with 'new' throughout entire file.",id:"Cari & ganti semua kemunculan teks di seluruh file."}],
  ["c1_27","cat-1","Command",'<span class="k">:%s/old/new/gc</span>',":%s/old/new/gc replace confirm",
    {en:"Search & Replace (confirm)",id:"Search & Replace (konfirmasi)",es:"Buscar y Reemplazar (confirmar)",de:"Suchen & Ersetzen (Bestätigung)","zh-CN":"确认后全局替换",ja:"確認付き全置換",ko:"확인 후 찾기 및 바꾸기",ru:"Поиск и замена с подтверждением"},
    {en:"Substitute all occurrences with confirmation prompt per replacement.",id:"Sama seperti di atas, tapi meminta konfirmasi tiap penggantian."}],
  ["c1_28","cat-1","Visual",'<span class="k">&gt;</span> · <span class="k">&lt;</span>',"> < indent outdent",
    {en:"Indent / Outdent",id:"Indent / Outdent",es:"Sangrar / Desangrar",de:"Einrücken / Ausrücken","zh-CN":"增加 / 减少缩进",ja:"インデント増減",ko:"들여쓰기 / 내어쓰기",ru:"Увеличить / уменьшить отступ"},
    {en:"Indent or outdent selected lines (remains in Visual mode for repeat).",id:"Tambah / kurangi indentasi selection (tetap dalam Visual mode untuk repeat)."}],
  ["c1_29","cat-1","Normal",'<span class="k">&lt;C-a&gt;</span> · <span class="k">&lt;C-x&gt;</span>',"<C-a> <C-x> increment decrement",
    {en:"Increment / Decrement number",id:"Increment / Decrement angka",es:"Incrementar / Decrementar número",de:"Zahl inkrementieren / dekrementieren","zh-CN":"数字自增 / 自减",ja:"数値のインクリメント/デクリメント",ko:"숫자 증가 / 감소",ru:"Увеличить / уменьшить число"},
    {en:"Add or subtract 1 from nearest number to cursor.",id:"Tambah / kurangi nilai angka terdekat dari kursor."}],
  ["c1_30","cat-1","Normal",'<span class="k">.</span>',". dot repeat",
    {en:"Repeat last change",id:"Repeat last change",es:"Repetir último cambio",de:"Letzte Änderung wiederholen","zh-CN":"重复上次编辑命令",ja:"直前の変更を繰り返す",ko:"마지막 변경 반복",ru:"Повторить последнее изменение"},
    {en:"Repeat the last text modification command.",id:"Ulangi perintah edit terakhir."}],

  /* Category 2 */
  ["c2_01","cat-2","Normal",'<span class="k">gg</span>',"gg top",
    {en:"Jump to top of file",id:"Lompat ke baris teratas",es:"Ir al inicio del archivo",de:"Zum Dateianfang springen","zh-CN":"跳转到文件首行",ja:"ファイルの先頭行へ移動",ko:"파일 첫 줄로 이동",ru:"В начало файла"},
    {en:"Move cursor to the very first line of the file.",id:"Pindah kursor ke baris pertama file."}],
  ["c2_02","cat-2","Normal",'<span class="k">G</span>',"G bottom",
    {en:"Jump to bottom of file",id:"Lompat ke baris terbawah",es:"Ir al final del archivo",de:"Zum Dateiende springen","zh-CN":"跳转到文件末行",ja:"ファイルの末尾行へ移動",ko:"파일 마지막 줄로 이동",ru:"В конец файла"},
    {en:"Move cursor to the last line of the file.",id:"Pindah kursor ke baris terakhir file."}],
  ["c2_03","cat-2","Normal",'<span class="k">^</span>',"^ non-blank",
    {en:"First non-blank character",id:"Awal baris (non-blank)",es:"Primer carácter no vacío",de:"Erstes nicht-leeres Zeichen","zh-CN":"行首非空字符",ja:"行頭の非空白文字へ",ko:"첫 공백 아닌 문자로",ru:"Первый непробельный символ"},
    {en:"Move cursor to first non-whitespace character in current line.",id:"Pindah ke karakter non-kosong pertama di baris."}],
  ["c2_04","cat-2","Normal",'<span class="k">0</span>',"0 col 0 start",
    {en:"Start of line (column 0)",id:"Awal baris (kolom 0)",es:"Inicio de línea (columna 0)",de:"Zeilenanfang (Spalte 0)","zh-CN":"行绝对起始位置 (列 0)",ja:"行頭 (列 0) へ移動",ko:"줄 맨 처음 (0번 열)",ru:"Начало строки (колонка 0)"},
    {en:"Move to very first column of line including whitespace.",id:"Pindah ke kolom paling awal baris, termasuk whitespace."}],
  ["c2_05","cat-2","Normal",'<span class="k">$</span>',"$ end line",
    {en:"End of line",id:"Akhir baris",es:"Fin de línea",de:"Zeilenende","zh-CN":"移动到行尾",ja:"行末へ移動",ko:"줄 끝으로 이동",ru:"Конец строки"},
    {en:"Move to the last character of current line.",id:"Pindah ke karakter terakhir baris."}],
  ["c2_06","cat-2","Command / Normal",'<span class="k">:{n}</span> · <span class="k">{n}G</span>',":n nG jump line",
    {en:"Jump to line number",id:"Lompat ke nomor baris",es:"Ir al número de línea",de:"Zu Zeilennummer springen","zh-CN":"跳转到指定行号",ja:"指定行番号へジャンプ",ko:"지정 줄 번호로 이동",ru:"Перейти к номеру строки"},
    {en:"Jump directly to line n (e.g. :42 or 42G).",id:"Loncat langsung ke baris ke-n, mis. :42 atau 42G."}],
  ["c2_07","cat-2","Normal",'<span class="k">w</span>',"w word next",
    {en:"Next word",id:"Kata berikutnya",es:"Palabra siguiente",de:"Nächstes Wort","zh-CN":"跳到下一个单词开头",ja:"次の単語の先頭へ",ko:"다음 단어 시작으로",ru:"К следующему слову"},
    {en:"Jump forward to start of next word.",id:"Loncat ke awal kata berikutnya."}],
  ["c2_08","cat-2","Normal",'<span class="k">b</span>',"b word prev",
    {en:"Previous word",id:"Kata sebelumnya",es:"Palabra anterior",de:"Vorheriges Wort","zh-CN":"跳到上一个单词开头",ja:"前の単語の先頭へ",ko:"이전 단어 시작으로",ru:"К предыдущему слову"},
    {en:"Jump backward to start of previous word.",id:"Loncat mundur ke awal kata sebelumnya."}],
  ["c2_09","cat-2","Normal",'<span class="k">e</span>',"e end word",
    {en:"End of word",id:"Akhir kata",es:"Fin de palabra",de:"Wortende","zh-CN":"跳到当前/下一个单词末尾",ja:"単語の末尾へ",ko:"단어 끝으로",ru:"К концу слова"},
    {en:"Jump forward to end of current/next word.",id:"Loncat ke akhir kata saat ini/berikutnya."}],
  ["c2_10","cat-2","Normal",'<span class="k">ge</span>',"ge prev end word",
    {en:"Previous end of word",id:"Akhir kata sebelumnya",es:"Fin de palabra anterior",de:"Vorheriges Wortende","zh-CN":"跳到上一个单词末尾",ja:"前の単語の末尾へ",ko:"이전 단어 끝으로",ru:"К концу предыдущего слова"},
    {en:"Jump backward to end of previous word.",id:"Loncat mundur ke akhir kata sebelumnya."}],
  ["c2_11","cat-2","Normal",'<span class="k">f{x}</span> / <span class="k">t{x}</span>',"fx tx find till",
    {en:"Find character in line (forward)",id:"Cari karakter di baris (maju)",es:"Buscar carácter en línea",de:"Zeichen in Zeile suchen","zh-CN":"行内向前查找字符",ja:"行内文字検索 (前方)",ko:"줄 내 문자 검색",ru:"Поиск символа в строке"},
    {en:"Jump onto (f) or till before (t) character x in current line.",id:"Lompat ke ('find') atau tepat sebelum ('till') karakter x di baris yang sama."}],
  ["c2_12","cat-2","Normal",'<span class="k">;</span> / <span class="k">,</span>',"; , repeat find",
    {en:"Repeat character search",id:"Ulangi pencarian karakter",es:"Repetir búsqueda de carácter",de:"Zeichensuche wiederholen","zh-CN":"重复行内查找",ja:"文字検索の繰り返し",ko:"문자 검색 반복",ru:"Повторить поиск символа"},
    {en:"Repeat last f/t character search in same (;) or reverse (,) direction.",id:"Ulangi f/t terakhir ke arah sama (;) atau berlawanan (,)."}],
  ["c2_13","cat-2","Normal",'<span class="k">%</span>',"% bracket match",
    {en:"Jump to matching bracket",id:"Lompat ke pasangan bracket",es:"Ir al paréntesis coincidente",de:"Zu passender Klammer springen","zh-CN":"匹配括号跳转",ja:"対応する括弧へ移動",ko:"일치하는 괄호로 이동",ru:"К парной скобке"},
    {en:"Jump between matching () [] {} pairs.",id:"Loncat ke pasangan () [] {} dari posisi kursor."}],
  ["c2_14","cat-2","Normal",'<span class="k">&lt;C-d&gt;</span> / <span class="k">&lt;C-u&gt;</span>',"<C-d> <C-u> scroll half page",
    {en:"Scroll half page down / up",id:"Scroll setengah halaman",es:"Desplazar media página abajo / arriba",de:"Halbe Seite runter / hoch scrollen","zh-CN":"半页向下 / 向上滚动",ja:"半画面スクロール",ko:"반 페이지 스크롤",ru:"Прокрутка на полстраницы"},
    {en:"Scroll view half-page down or up while moving cursor.",id:"Scroll turun / naik setengah layar sambil kursor ikut pindah."}],
  ["c2_15","cat-2","Normal",'<span class="k">{</span> / <span class="k">}</span>',"{ } paragraph",
    {en:"Previous / next paragraph",id:"Paragraf berikutnya / sebelumnya",es:"Párrafo anterior / siguiente",de:"Vorheriger / nächster Absatz","zh-CN":"上一个 / 下一个段落",ja:"前/次の段落へ移動",ko:"이전 / 다음 단락으로",ru:"Предыдущий / следующий абзац"},
    {en:"Jump backward ({) or forward (}) by empty paragraph lines.",id:"Lompat ke paragraf (blok kosong) berikutnya / sebelumnya."}],
  ["c2_16","cat-2","Normal",'<span class="k">gd</span>',"gd definition lsp",
    {en:"Go to Definition (LSP)",id:"Go to Definition (LSP)",es:"Ir a definición (LSP)",de:"Zur Definition gehen (LSP)","zh-CN":"跳转到定义 (LSP)",ja:"定義へジャンプ (LSP)",ko:"정의로 이동 (LSP)",ru:"К определению (LSP)"},
    {en:"Jump directly to definition of symbol under cursor via LSP.",id:"Lompat ke definisi simbol/fungsi/variabel di bawah kursor."}],
  ["c2_17","cat-2","Normal",'<span class="k">gr</span>',"gr references lsp",
    {en:"Go to References (LSP)",id:"Go to References (LSP)",es:"Ver referencias (LSP)",de:"Referenzen anzeigen (LSP)","zh-CN":"查找所有引用 (LSP)",ja:"参照一覧を表示 (LSP)",ko:"참조 목록 확인 (LSP)",ru:"Показать ссылки (LSP)"},
    {en:"List all project references of symbol under cursor.",id:"Tampilkan semua referensi/pemakaian simbol tersebut dalam project."}],
  ["c2_18","cat-2","Normal",'<span class="k">gI</span>',"gI implementation lsp",
    {en:"Go to Implementation (LSP)",id:"Go to Implementation (LSP)",es:"Ir a implementación (LSP)",de:"Zur Implementierung gehen (LSP)","zh-CN":"跳转到具体实现 (LSP)",ja:"実装へジャンプ (LSP)",ko:"구현부로 이동 (LSP)",ru:"К реализации (LSP)"},
    {en:"Jump to concrete implementation of interface or method.",id:"Lompat ke implementasi konkret dari interface/fungsi abstrak."}],
  ["c2_19","cat-2","Normal",'<span class="k">gy</span>',"gy type definition lsp",
    {en:"Go to Type Definition (LSP)",id:"Go to Type Definition (LSP)",es:"Ir a definición de tipo (LSP)",de:"Zur Typdefinition gehen (LSP)","zh-CN":"跳转到类型定义 (LSP)",ja:"型定義へジャンプ (LSP)",ko:"타입 정의로 이동 (LSP)",ru:"К определению типа (LSP)"},
    {en:"Jump to type definition of symbol under cursor.",id:"Lompat ke definisi tipe data dari simbol di bawah kursor."}],
  ["c2_20","cat-2","Normal",'<span class="k">gD</span>',"gD declaration lsp",
    {en:"Go to Declaration (LSP)",id:"Go to Declaration (LSP)",es:"Ir a declaración (LSP)",de:"Zur Deklaration gehen (LSP)","zh-CN":"跳转到符号声明 (LSP)",ja:"宣言へジャンプ (LSP)",ko:"선언부로 이동 (LSP)",ru:"К объявлению (LSP)"},
    {en:"Jump to declaration of symbol under cursor.",id:"Lompat ke deklarasi (berbeda dari definisi, tergantung bahasa)."}],
  ["c2_21","cat-2","Normal",'<span class="k">K</span>',"K hover doc lsp",
    {en:"Hover Documentation (LSP)",id:"Hover Documentation (LSP)",es:"Documentación flotante (LSP)",de:"Hover-Dokumentation (LSP)","zh-CN":"悬浮文档提示 (LSP)",ja:"ホバードキュメント表示 (LSP)",ko:"문서 팝업 확인 (LSP)",ru:"Документация под курсором (LSP)"},
    {en:"Show hover info and docstring for symbol under cursor.",id:"Tampilkan dokumentasi/hover info simbol di bawah kursor."}],

  /* Category 3 */
  ["c3_01","cat-3","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">e</span>',"<leader>+e <leader>e leader e neotree toggle",
    {en:"Toggle File Explorer",id:"Toggle File Explorer",es:"Alternar explorador de archivos",de:"Dateiexplorer umschalten","zh-CN":"打开/关闭文件树",ja:"ファイルツリー開閉",ko:"파일 탐색기 토글",ru:"Переключить проводник"},
    {en:"Open or close Neo-tree sidebar on current project root.",id:"Buka / tutup sidebar Neo-tree pada root direktori project."}],
  ["c3_02","cat-3","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">fe</span>',"<leader>+fe <leader>fe explorer root",
    {en:"Explorer (root dir)",id:"Explorer (root dir)",es:"Explorador (directorio raíz)",de:"Explorer (Projektwurzel)","zh-CN":"根目录打开文件树",ja:"プロジェクトルートで開く",ko:"루트 탐색기 열기",ru:"Проводник (корень)"},
    {en:"Open Neo-tree sidebar rooted at project root directory.",id:"Alternatif membuka Neo-tree yang berpusat di root project."}],
  ["c3_03","cat-3","Normal",'<span class="k">&lt;C-h&gt;</span>',"<C-h> ctrl-h sidebar focus",
    {en:"Focus to sidebar",id:"Fokus ke sidebar",es:"Foco a la barra lateral",de:"Fokus auf Seitenleiste","zh-CN":"焦点切换至侧边栏",ja:"サイドバーへフォーカス",ko:"사이드바로 포커스",ru:"Фокус на боковую панель"},
    {en:"Move window focus from editor buffer into Neo-tree sidebar.",id:"Dari buffer aktif, pindah fokus window ke Neo-tree tanpa menutup buffer."}],
  ["c3_04","cat-3","Normal",'<span class="k">&lt;C-l&gt;</span>',"<C-l> ctrl-l editor focus",
    {en:"Return to buffer",id:"Kembali ke buffer",es:"Volver al editor",de:"Zurück zum Puffer","zh-CN":"从文件树返回编辑器",ja:"エディタバッファに戻る",ko:"에디터 버퍼로 복귀",ru:"Вернуться в редактор"},
    {en:"Move window focus from Neo-tree back to active editor.",id:"Dari Neo-tree, kembali fokus ke window editor/buffer."}],
  ["c3_05","cat-3","NeoTree",'<span class="k">&lt;CR&gt;</span> / <span class="k">o</span>',"<CR> o enter open",
    {en:"Open file / toggle folder",id:"Buka file / folder",es:"Abrir archivo / carpeta",de:"Datei öffnen / Ordner toggeln","zh-CN":"打开文件 / 展开折叠文件夹",ja:"ファイルを開く / フォルダ展開",ko:"파일 열기 / 폴더 토글",ru:"Открыть файл / папку"},
    {en:"Open selected file, or expand/collapse folder.",id:"Buka file terpilih, atau expand/collapse folder."}],
  ["c3_06","cat-3","NeoTree",'<span class="k">a</span>',"a add new file",
    {en:"Create New File",id:"Buat File Baru",es:"Crear archivo nuevo",de:"Neue Datei erstellen","zh-CN":"新建文件",ja:"新規ファイル作成",ko:"새 파일 생성",ru:"Создать новый файл"},
    {en:"Add a new file — type filename with extension and press Enter.",id:"Tambah file baru — ketik nama lengkap dengan ekstensi, lalu Enter."}],
  ["c3_07","cat-3","NeoTree",'<span class="k">a</span>',"a add new folder",
    {en:"Create New Folder",id:"Buat Folder Baru",es:"Crear carpeta nueva",de:"Neuen Ordner erstellen","zh-CN":"新建文件夹",ja:"新規フォルダ作成",ko:"새 폴더 생성",ru:"Создать новую папку"},
    {en:"Add a new folder — terminate name with a slash (e.g. components/).",id:"Sama seperti buat file, tapi akhiri nama dengan garis miring."}],
  ["c3_08","cat-3","NeoTree",'<span class="k">d</span>',"d delete neotree",
    {en:"Delete file / folder",id:"Hapus file/folder",es:"Eliminar archivo/carpeta",de:"Datei/Ordner löschen","zh-CN":"删除文件或文件夹",ja:"ファイル/フォルダ削除",ko:"파일/폴더 삭제",ru:"Удалить файл / папку"},
    {en:"Delete selected item (will prompt for confirmation).",id:"Hapus item terpilih (akan meminta konfirmasi)."}],
  ["c3_09","cat-3","NeoTree",'<span class="k">r</span>',"r rename neotree",
    {en:"Rename file / folder",id:"Rename file/folder",es:"Renombrar archivo/carpeta",de:"Datei/Ordner umbenennen","zh-CN":"重命名文件或文件夹",ja:"名前変更 (リネーム)",ko:"파일/폴더 이름 변경",ru:"Переименовать файл / папку"},
    {en:"Rename the currently selected item inline.",id:"Ganti nama item terpilih secara inline."}],
  ["c3_10","cat-3","NeoTree",'<span class="k">c</span>',"c copy neotree",
    {en:"Copy file",id:"Copy file",es:"Copiar archivo",de:"Datei kopieren","zh-CN":"复制文件",ja:"ファイルをコピー",ko:"파일 복사",ru:"Скопировать файл"},
    {en:"Copy selected item, ready to paste elsewhere.",id:"Copy item terpilih, siap di-paste ke lokasi lain."}],
  ["c3_11","cat-3","NeoTree",'<span class="k">x</span>',"x cut move neotree",
    {en:"Cut file (move)",id:"Cut file",es:"Cortar archivo (mover)",de:"Datei ausschneiden (verschieben)","zh-CN":"剪切/移动文件",ja:"ファイルを切り取り (移動)",ko:"파일 잘라내기 (이동)",ru:"Вырезать файл (переместить)"},
    {en:"Cut selected item, ready to move/paste elsewhere.",id:"Cut (move) item terpilih, siap di-paste ke lokasi lain."}],
  ["c3_12","cat-3","NeoTree",'<span class="k">p</span>',"p paste neotree",
    {en:"Paste file",id:"Paste file",es:"Pegar archivo",de:"Datei einfügen","zh-CN":"粘贴文件或文件夹",ja:"ファイルを貼り付け",ko:"파일 붙여넣기",ru:"Вставить файл"},
    {en:"Paste previously copied or cut item into directory.",id:"Tempel file/folder yang sudah di-copy atau di-cut sebelumnya."}],
  ["c3_13","cat-3","NeoTree",'<span class="k">v</span>',"v split vertical neotree",
    {en:"Open in Vertical Split",id:"Buka di Vertical Split",es:"Abrir en división vertical",de:"In vertikalem Split öffnen","zh-CN":"在纵向分屏中打开",ja:"垂直分割で開く",ko:"세로 분할 창으로 열기",ru:"Открыть в вертикальном сплите"},
    {en:"Open selected file inside a new vertical window split.",id:"Buka file terpilih dalam split vertikal baru."}],
  ["c3_14","cat-3","NeoTree",'<span class="k">s</span>',"s split horizontal neotree",
    {en:"Open in Horizontal Split",id:"Buka di Horizontal Split",es:"Abrir en división horizontal",de:"In horizontalem Split öffnen","zh-CN":"在横向分屏中打开",ja:"水平分割で開く",ko:"가로 분할 창으로 열기",ru:"Открыть dalam horizontalen split"},
    {en:"Open selected file inside a new horizontal window split.",id:"Buka file terpilih dalam split horizontal baru."}],
  ["c3_15","cat-3","NeoTree",'<span class="k">R</span>',"R refresh tree",
    {en:"Refresh folder structure",id:"Refresh struktur folder",es:"Actualizar estructura",de:"Ordneransicht aktualisieren","zh-CN":"刷新文件树",ja:"ツリー再読み込み",ko:"폴더 트리 새로고침",ru:"Обновить дерево файлов"},
    {en:"Refresh tree view after external file system changes.",id:"Refresh tampilan tree — berguna setelah perubahan file dari luar Neovim."}],
  ["c3_16","cat-3","NeoTree",'<span class="k">H</span>',"H hidden dotfiles",
    {en:"Toggle hidden / dotfiles",id:"Toggle hidden/dotfiles",es:"Alternar archivos ocultos",de:"Versteckte Dateien umschalten","zh-CN":"显示/隐藏点文件及隐藏文件",ja:"隠しファイル表示切替",ko:"숨김 파일 토글",ru:"Показать / скрыть скрытые файлы"},
    {en:"Show or hide dotfiles and hidden files (.env, .git).",id:"Tampilkan / sembunyikan file tersembunyi (dotfiles) seperti .env, .git."}],
  ["c3_17","cat-3","NeoTree",'<span class="k">y</span>',"y copy path",
    {en:"Copy path to clipboard",id:"Copy path ke clipboard",es:"Copiar ruta al portapapeles",de:"Pfad in Zwischenablage kopieren","zh-CN":"复制路径到剪贴板",ja:"パスをコピー",ko:"경로 복사",ru:"Скопировать путь к файлу"},
    {en:"Copy relative or absolute file path to clipboard.",id:"Copy path absolut/relatif file terpilih ke clipboard."}],
  ["c3_18","cat-3","NeoTree",'<span class="k">q</span>',"q quit close neotree",
    {en:"Close Neo-tree",id:"Tutup Neo-tree",es:"Cerrar Neo-tree",de:"Neo-tree schließen","zh-CN":"关闭文件树",ja:"Neo-tree を閉じる",ko:"Neo-tree 닫기",ru:"Закрыть Neo-tree"},
    {en:"Close the active Neo-tree window.",id:"Tutup window Neo-tree."}],
  ["c3_19","cat-3","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">fp</span>',"<leader>+fp <leader>fp projects switch",
    {en:"Switch / Open Project",id:"Switch / Buka Project",es:"Cambiar / Abrir proyecto",de:"Projekt wechseln / öffnen","zh-CN":"切换/打开最近项目",ja:"プロジェクト切り替え",ko:"프로젝트 전환",ru:"Переключить проект"},
    {en:"Open recent projects picker to switch workspace (project.nvim).",id:"Buka picker daftar project sebelumnya untuk berpindah workspace."}],

  /* Category 4 */
  ["c4_01","cat-4","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">&lt;space&gt;</span> · <span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">ff</span>',"<leader>+<space> <leader>ff find files open",
    {en:"Quick Open / Find Files",id:"Quick Open / Find Files",es:"Abrir rápido / Buscar archivos",de:"Dateien suchen / Schnell öffnen","zh-CN":"全局快速查找文件",ja:"ファイル高速検索 (Find Files)",ko:"빠른 파일 찾기",ru:"Быстрый поиск файлов"},
    {en:"Fuzzy search and open files across the entire project.",id:"Cari nama file di seluruh project dengan fuzzy search."}],
  ["c4_02","cat-4","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">sg</span> · <span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">/</span>',"<leader>+sg <leader>+/<leader>sg <leader>/ live grep search",
    {en:"Live Grep",id:"Live Grep",es:"Grep en vivo",de:"Live-Grep","zh-CN":"全局实时文本检索 (Live Grep)",ja:"リアルタイム全文検索 (Live Grep)",ko:"실시간 텍스트 검색",ru:"Живой поиск текста (Live Grep)"},
    {en:"Search text string across entire project in real-time.",id:"Cari string/teks di seluruh isi file dalam project secara real-time."}],
  ["c4_03","cat-4","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">sw</span>',"<leader>+sw <leader>sw grep word cursor",
    {en:"Grep word under cursor",id:"Grep kata di bawah kursor",es:"Buscar palabra bajo el cursor",de:"Wort unter Cursor suchen","zh-CN":"在项目中搜索光标所在词",ja:"カーソル位置の単語を検索",ko:"커서 위치 단어 검색",ru:"Поиск слова под курсором"},
    {en:"Search project for string currently under cursor.",id:"Cari langsung kata yang sedang berada di bawah kursor ke seluruh project."}],
  ["c4_04","cat-4","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">fr</span>',"<leader>+fr <leader>fr recent oldfiles",
    {en:"Recent Files",id:"Recent Files",es:"Archivos recientes",de:"Zuletzt geöffnete Dateien","zh-CN":"打开最近访问过的文件",ja:"最近開いたファイル",ko:"최근 열었던 파일 목록",ru:"Недавние файлы"},
    {en:"Show and pick from recently opened files (oldfiles).",id:"Tampilkan daftar file yang baru-baru ini dibuka (oldfiles)."}],
  ["c4_05","cat-4","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">fb</span> · <span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">,</span>',"<leader>+fb <leader>+, buffers list",
    {en:"Open Buffers List",id:"Daftar Buffer Terbuka",es:"Lista de buffers abiertos",de:"Geöffnete Puffer auflisten","zh-CN":"查看当前打开的缓冲区列表",ja:"開いているバッファ一覧",ko:"열린 버퍼 목록",ru:"Список открытых буферов"},
    {en:"List and pick from currently loaded editor buffers.",id:"Tampilkan & pilih dari daftar buffer yang sedang terbuka."}],
  ["c4_06","cat-4","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">sb</span>',"<leader>+sb <leader>sb search buffer",
    {en:"Search in current buffer",id:"Cari di file saat ini",es:"Buscar en buffer actual",de:"Im aktuellen Puffer suchen","zh-CN":"在当前缓冲区内模糊搜索",ja:"現在のバッファ内を検索",ko:"현재 버퍼 내 검색",ru:"Поиск в текущем буфере"},
    {en:"Fuzzy search lines only within the active buffer.",id:"Fuzzy search baris teks hanya di buffer aktif."}],
  ["c4_07","cat-4","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">sh</span>',"<leader>+sh <leader>sh help tags",
    {en:"Search Help / Docs",id:"Cari Help / Dokumentasi",es:"Buscar ayuda / Documentación",de:"Hilfe / Dokumentation suchen","zh-CN":"查找 Neovim 帮助文档",ja:"ヘルプ/ドキュメント検索",ko:"도움말 문서 검색",ru:"Поиск в справке"},
    {en:"Search Neovim and plugin help documentation tags.",id:"Cari topik pada help-doc Neovim/plugin."}],
  ["c4_08","cat-4","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">sk</span>',"<leader>+sk <leader>sk search keymaps",
    {en:"Search Keymaps",id:"Cari Daftar Keymap",es:"Buscar atajos registrados",de:"Tastenkombinationen suchen","zh-CN":"浏览检索所有快捷键",ja:"登録キーマップ検索",ko:"등록된 단축키 검색",ru:"Поиск назначений клавиш"},
    {en:"Browse and fuzzy search all currently active keymaps.",id:"Browse seluruh keymap yang terdaftar saat ini."}],
  ["c4_09","cat-4","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">sr</span>',"<leader>+sr <leader>sr resume search",
    {en:"Resume Last Search",id:"Resume Pencarian Terakhir",es:"Reanudar última búsqueda",de:"Letzte Suche fortsetzen","zh-CN":"恢复上一次查找会话",ja:"前回の検索を再開",ko:"마지막 검색 세션 재개",ru:"Возобновить последний поиск"},
    {en:"Re-open last Telescope picker session and state.",id:"Lanjutkan/buka kembali sesi picker Telescope terakhir."}],

  /* Category 5 */
  ["c5_01","cat-5","Normal",'<span class="k">]b</span> · <span class="k">&lt;S-l&gt;</span>',"]b <S-l> next buffer",
    {en:"Next buffer",id:"Buffer berikutnya",es:"Siguiente buffer",de:"Nächster Puffer","zh-CN":"切换到下一个缓冲区",ja:"次のバッファへ移動",ko:"다음 버퍼로 이동",ru:"Следующий буфер"},
    {en:"Switch to next buffer tab on bufferline.",id:"Pindah ke tab buffer berikutnya pada bufferline."}],
  ["c5_02","cat-5","Normal",'<span class="k">[b</span> · <span class="k">&lt;S-h&gt;</span>',"[b <S-h> prev buffer",
    {en:"Previous buffer",id:"Buffer sebelumnya",es:"Buffer anterior",de:"Vorheriger Puffer","zh-CN":"切换到上一个缓冲区",ja:"前のバッファへ移動",ko:"이전 버퍼로 이동",ru:"Предыдущий буфер"},
    {en:"Switch to previous buffer tab on bufferline.",id:"Pindah ke tab buffer sebelumnya pada bufferline."}],
  ["c5_03","cat-5","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">bd</span>',"<leader>+bd <leader>bd close buffer delete",
    {en:"Close active buffer",id:"Tutup Buffer Aktif",es:"Cerrar buffer activo",de:"Aktiven Puffer schließen","zh-CN":"安全关闭当前缓冲区",ja:"現在のバッファを閉じる",ko:"현재 버퍼 닫기",ru:"Закрыть активный буфер"},
    {en:"Close current buffer without disrupting window split layout.",id:"Tutup buffer aktif tanpa merusak layout split yang sedang berjalan."}],
  ["c5_04","cat-5","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">bD</span>',"<leader>+bD <leader>bD force close buffer",
    {en:"Force close buffer",id:"Force Tutup Buffer",es:"Forzar cierre de buffer",de:"Puffer erzwingend schließen","zh-CN":"强制关闭当前缓冲区",ja:"バッファを強制終了",ko:"버퍼 강제 닫기",ru:"Принудительно закрыть буфер"},
    {en:"Forcefully close buffer, discarding unsaved modifications.",id:"Tutup buffer secara paksa, termasuk buang perubahan belum tersimpan."}],
  ["c5_05","cat-5","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">w|</span> · <span class="k">&lt;C-w&gt;v</span>',"<leader>+w| <C-w>v split vertical",
    {en:"Split window vertically",id:"Split Vertikal",es:"Dividir ventana verticalmente",de:"Fenster vertikal teilen","zh-CN":"纵向分屏窗口",ja:"垂直分割ウィンドウ作成",ko:"세로 분할 창 열기",ru:"Вертикальный сплит"},
    {en:"Open new window split vertically (side by side).",id:"Buka split window baru secara vertikal (berdampingan kiri-kanan)."}],
  ["c5_06","cat-5","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">w-</span> · <span class="k">&lt;C-w&gt;s</span>',"<leader>+w- <C-w>s split horizontal",
    {en:"Split window horizontally",id:"Split Horizontal",es:"Dividir ventana horizontalmente",de:"Fenster horizontal teilen","zh-CN":"横向分屏窗口",ja:"水平分割ウィンドウ作成",ko:"가로 분할 창 열기",ru:"Горизонтальный сплит"},
    {en:"Open new window split horizontally (top and bottom).",id:"Buka split window baru secara horizontal (atas-bawah)."}],
  ["c5_07","cat-5","Normal",'<span class="k">&lt;C-h&gt;</span>',"<C-h> ctrl-h window left",
    {en:"Navigate to window left",id:"Navigasi ke window kiri",es:"Foco a ventana izquierda",de:"Fokus nach links","zh-CN":"聚焦左侧窗口",ja:"左のウィンドウへ移動",ko:"왼쪽 창으로 이동",ru:"К окну слева"},
    {en:"Move focus to the split window on the left.",id:"Pindah fokus ke split di sebelah kiri."}],
  ["c5_08","cat-5","Normal",'<span class="k">&lt;C-j&gt;</span>',"<C-j> ctrl-j window down",
    {en:"Navigate to window below",id:"Navigasi ke window bawah",es:"Foco a ventana inferior",de:"Fokus nach unten","zh-CN":"聚焦下方窗口",ja:"下のウィンドウへ移動",ko:"아래쪽 창으로 이동",ru:"К окну снизу"},
    {en:"Move focus to the split window below.",id:"Pindah fokus ke split di bawah."}],
  ["c5_09","cat-5","Normal",'<span class="k">&lt;C-k&gt;</span>',"<C-k> ctrl-k window up",
    {en:"Navigate to window above",id:"Navigasi ke window atas",es:"Foco a ventana superior",de:"Fokus nach oben","zh-CN":"聚焦上方窗口",ja:"上のウィンドウへ移動",ko:"위쪽 창으로 이동",ru:"К окну сверху"},
    {en:"Move focus to the split window above.",id:"Pindah fokus ke split di atas."}],
  ["c5_10","cat-5","Normal",'<span class="k">&lt;C-l&gt;</span>',"<C-l> ctrl-l window right",
    {en:"Navigate to window right",id:"Navigasi ke window kanan",es:"Foco a ventana derecha",de:"Fokus nach rechts","zh-CN":"聚焦右侧窗口",ja:"右のウィンドウへ移動",ko:"오른쪽 창으로 이동",ru:"К окну справа"},
    {en:"Move focus to the split window on the right.",id:"Pindah fokus ke split di sebelah kanan."}],
  ["c5_11","cat-5","Normal",'<span class="k">&lt;C-Up&gt;</span> / <span class="k">&lt;C-Down&gt;</span>',"<C-Up> <C-Down> resize height",
    {en:"Resize window height",id:"Resize window (tinggi)",es:"Cambiar altura de ventana",de:"Fensterhöhe anpassen","zh-CN":"调整窗口高度",ja:"ウィンドウ高さを調整",ko:"창 높이 조절",ru:"Изменить высоту окна"},
    {en:"Increase or decrease active window height.",id:"Tambah / kurangi tinggi window aktif."}],
  ["c5_12","cat-5","Normal",'<span class="k">&lt;C-Left&gt;</span> / <span class="k">&lt;C-Right&gt;</span>',"<C-Left> <C-Right> resize width",
    {en:"Resize window width",id:"Resize window (lebar)",es:"Cambiar ancho de ventana",de:"Fensterbreite anpassen","zh-CN":"调整窗口宽度",ja:"ウィンドウ幅を調整",ko:"창 너비 조절",ru:"Изменить ширину окна"},
    {en:"Decrease or increase active window width.",id:"Kurangi / tambah lebar window aktif."}],
  ["c5_13","cat-5","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">wd</span> · <span class="k">&lt;C-w&gt;c</span>',"<leader>+wd <C-w>c close window",
    {en:"Close Active Window",id:"Tutup Window Aktif",es:"Cerrar ventana activa",de:"Aktives Fenster schließen","zh-CN":"关闭当前分割窗口",ja:"現在のウィンドウを閉じる",ko:"현재 창 닫기",ru:"Закрыть текущее окно"},
    {en:"Close current window split (buffer stays loaded if opened elsewhere).",id:"Tutup split window yang sedang aktif."}],
  ["c5_14","cat-5","Normal",'<span class="k">&lt;C-w&gt;=</span>',"<C-w>= equalize windows",
    {en:"Equalize windows",id:"Equalize windows",es:"Igualar ventanas",de:"Fenstergrößen angleichen","zh-CN":"均等平分所有窗口尺寸",ja:"全ウィンドウのサイズを均等化",ko:"모든 창 크기 균등화",ru:"Уравнять размеры окон"},
    {en:"Make all window splits equal width and height in current tab.",id:"Samakan ukuran semua split window dalam tab aktif."}],

  /* Category 6 */
  ["c6_01","cat-6","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">gg</span>',"<leader>+gg <leader>gg lazygit",
    {en:"Open LazyGit UI",id:"Buka LazyGit UI",es:"Abrir interfaz LazyGit",de:"LazyGit UI öffnen","zh-CN":"打开 LazyGit 终端弹窗",ja:"LazyGit UI を開く",ko:"LazyGit UI 열기",ru:"Открыть интерфейс LazyGit"},
    {en:"Open full floating terminal LazyGit interface within Neovim.",id:"Buka antarmuka LazyGit penuh (floating terminal) di dalam Neovim."}],
  ["c6_02","cat-6","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">gs</span>',"<leader>+gs <leader>gs git status",
    {en:"Git Status",id:"Git Status",es:"Estado de Git",de:"Git-Status","zh-CN":"Git 状态",ja:"Git ステータス表示",ko:"Git 상태 확인",ru:"Статус Git"},
    {en:"Show modified/staged git files via picker.",id:"Tampilkan status Git melalui picker."}],
  ["c6_03","cat-6","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">gb</span>',"<leader>+gb <leader>gb git blame line",
    {en:"Git Blame (line)",id:"Git Blame (baris aktif)",es:"Git Blame (línea)",de:"Git Blame (aktive Zeile)","zh-CN":"查看当前行 Git Blame",ja:"行の Git Blame 表示",ko:"현재 줄 Git Blame",ru:"Git Blame текущей строки"},
    {en:"Show author and commit information for line under cursor.",id:"Tampilkan info commit/author terakhir untuk baris tempat kursor berada."}],
  ["c6_04","cat-6","Normal",'<span class="k">]h</span>',"]h next hunk",
    {en:"Next hunk",id:"Hunk berikutnya",es:"Siguiente hunk",de:"Nächster Hunk","zh-CN":"跳转到下一个 Git 改动块",ja:"次の変更ブロック (Hunk)",ko:"다음 Git 변경 단위",ru:"Следующий ханк"},
    {en:"Jump forward to next Git change hunk in buffer.",id:"Lompat ke blok perubahan (hunk) Git berikutnya di buffer."}],
  ["c6_05","cat-6","Normal",'<span class="k">[h</span>',"[h prev hunk",
    {en:"Previous hunk",id:"Hunk sebelumnya",es:"Hunk anterior",de:"Vorheriger Hunk","zh-CN":"跳转到上一个 Git 改动块",ja:"前の変更ブロック (Hunk)",ko:"이전 Git 변경 단위",ru:"Предыдущий ханк"},
    {en:"Jump backward to previous Git change hunk in buffer.",id:"Lompat ke blok perubahan (hunk) Git sebelumnya di buffer."}],
  ["c6_06","cat-6","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">ghp</span>',"<leader>+ghp <leader>ghp preview hunk",
    {en:"Preview Hunk",id:"Preview Hunk",es:"Previsualizar hunk",de:"Hunk-Vorschau","zh-CN":"预览代码块改动",ja:"ハンクの差分プレビュー",ko:"변경 단위 미리보기",ru:"Предпросмотр ханка"},
    {en:"Show floating diff popup for change hunk under cursor.",id:"Tampilkan popup diff untuk hunk di posisi kursor."}],
  ["c6_07","cat-6","Normal / Visual",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">ghs</span>',"<leader>+ghs <leader>ghs stage hunk",
    {en:"Stage Hunk",id:"Stage Hunk",es:"Preparar hunk (Stage)",de:"Hunk stagen","zh-CN":"暂存代码改动块",ja:"ハンクをステージ",ko:"변경 단위 스테이징",ru:"Стейджить ханк"},
    {en:"Stage hunk under cursor (or selected lines).",id:"Stage perubahan hunk di posisi kursor (atau seluruh selection)."}],
  ["c6_08","cat-6","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">ghr</span>',"<leader>+ghr <leader>ghr reset hunk undo",
    {en:"Reset / Undo Hunk",id:"Reset / Undo Hunk",es:"Revertir hunk",de:"Hunk zurücksetzen","zh-CN":"撤销代码块改动",ja:"ハンクの変更を破棄",ko:"변경 단위 되돌리기",ru:"Сбросить ханк"},
    {en:"Revert change hunk under cursor to last committed state.",id:"Buang (revert) perubahan pada hunk di posisi kursor."}],
  ["c6_09","cat-6","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">ghu</span>',"<leader>+ghu <leader>ghu unstage hunk",
    {en:"Unstage Hunk",id:"Unstage Hunk",es:"Quitar hunk del stage",de:"Hunk unstagen","zh-CN":"取消暂存代码块",ja:"ハンクのステージ解除",ko:"변경 단위 스테이징 취소",ru:"Анстейджить ханк"},
    {en:"Unstage previously staged change hunk.",id:"Batalkan staging pada hunk yang sudah di-stage sebelumnya."}],
  ["c6_10","cat-6","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">ghb</span>',"<leader>+ghb <leader>ghb blame popup",
    {en:"Blame Line (full popup)",id:"Blame Line (full popup)",es:"Blame completo (popup)",de:"Vollständiges Blame-Popup","zh-CN":"完整行 Blame 浮窗",ja:"詳細 Blame ポップアップ",ko:"전체 Blame 팝업",ru:"Подробный Blame (popup)"},
    {en:"Show detailed git blame popup with commit msg, date, and author.",id:"Tampilkan popup blame lengkap untuk baris aktif."}],
  ["c6_11","cat-6","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">ghd</span>',"<leader>+ghd <leader>ghd diff this",
    {en:"Diff This (file)",id:"Diff This (file)",es:"Diff del archivo",de:"Diff dieser Datei","zh-CN":"文件差异对比",ja:"ファイルの差分比較",ko:"현재 파일 Diff 비교",ru:"Diff файла"},
    {en:"Open side-by-side diff between active buffer and HEAD.",id:"Buka diff split antara versi file saat ini dengan HEAD."}],

  /* Category 7 */
  ["c7_01","cat-7","Normal / Insert",'<span class="k">&lt;C-s&gt;</span> · <span class="k">:w</span>',"<C-s> :w save write",
    {en:"Save File",id:"Simpan File",es:"Guardar archivo",de:"Datei speichern","zh-CN":"保存当前文件",ja:"ファイルを保存",ko:"파일 저장",ru:"Сохранить файл"},
    {en:"Save active buffer to disk (<C-s> works directly inside Insert mode).",id:"Simpan buffer aktif ke disk."}],
  ["c7_02","cat-7","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">qq</span> · <span class="k">:qa</span>',"<leader>+qq <leader>qq :qa quit",
    {en:"Quit All",id:"Keluar (Quit All)",es:"Salir de todo",de:"Alles beenden","zh-CN":"退出 Neovim",ja:"すべて終了 (Quit All)",ko:"전체 종료",ru:"Выйти из Neovim"},
    {en:"Quit Neovim; prompts if there are unsaved modifications.",id:"Keluar dari seluruh Neovim."}],
  ["c7_03","cat-7","Command",'<span class="k">:qa!</span>',":qa! force quit",
    {en:"Force Quit (discard)",id:"Keluar Paksa (buang perubahan)",es:"Forzar salida (descartar)",de:"Beenden erzwingen (verwerfen)","zh-CN":"强制退出",ja:"強制終了 (保存しない)",ko:"강제 종료",ru:"Принудительный выход"},
    {en:"Exit Neovim immediately, discarding all unsaved changes.",id:"Keluar dari seluruh Neovim tanpa menyimpan."}],
  ["c7_04","cat-7","Command",'<span class="k">:wqa</span>',":wqa save quit write quit",
    {en:"Save and Quit All",id:"Simpan lalu Keluar",es:"Guardar y salir de todo",de:"Speichern und alles beenden","zh-CN":"保存并退出所有文件",ja:"全保存して終了",ko:"저장 후 전체 종료",ru:"Сохранить и выйти"},
    {en:"Save all modified buffers and safely exit Neovim.",id:"Simpan semua buffer yang berubah, lalu keluar sepenuhnya."}],
  ["c7_05","cat-7","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">l</span>',"<leader>+l <leader>l lazy plugins",
    {en:"Open Lazy Plugin Manager",id:"Buka Lazy Plugin Manager",es:"Gestor de plugins Lazy",de:"Lazy Plugin-Manager öffnen","zh-CN":"打开 Lazy 插件管理器",ja:"Lazy プラグインマネージャ",ko:"Lazy 플러그인 관리자",ru:"Менеджер плагинов Lazy"},
    {en:"Open lazy.nvim UI to inspect, install, update, or clean plugins.",id:"Buka UI lazy.nvim untuk install/update/hapus/cek status plugin."}],
  ["c7_06","cat-7","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">cm</span>',"<leader>+cm <leader>cm mason lsp",
    {en:"Open Mason (LSP / Formatter)",id:"Buka Mason (LSP/Formatter Manager)",es:"Abrir Mason (LSP / Formateador)",de:"Mason UI öffnen","zh-CN":"打开 Mason 工具管理器",ja:"Mason (LSP/Formatter) を開く",ko:"Mason 도구 관리자 열기",ru:"Открыть Mason (LSP/Форматтеры)"},
    {en:"Open Mason UI to manage LSP servers, linters, and formatters.",id:"Buka UI Mason untuk install/uninstall LSP server, formatter, dan linter."}],
  ["c7_07","cat-7","Command",'<span class="k">:checkhealth</span>',":checkhealth health doctor",
    {en:"Check Neovim Health",id:"Cek Kesehatan Neovim",es:"Verificar estado de Neovim",de:"Neovim Health-Check","zh-CN":"运行 Neovim 健康体检",ja:"ヘルスチェック実行",ko:"Neovim 상태 진단",ru:"Проверка состояния Neovim"},
    {en:"Run comprehensive system diagnostics on config and dependencies.",id:"Diagnostik menyeluruh konfigurasi, dependency, dan plugin Neovim."}],
  ["c7_08","cat-7","Normal",'<span class="k leader">&lt;leader&gt;</span><span class="plus">+</span><span class="k">cf</span>',"<leader>+cf <leader>cf format conform lsp",
    {en:"Format Buffer (LSP)",id:"Format Buffer (LSP)",es:"Formatear buffer (LSP)",de:"Puffer formatieren (LSP)","zh-CN":"格式化当前代码文件",ja:"バッファをフォーマット",ko:"현재 버퍼 코드 포맷팅",ru:"Форматировать буфер (LSP)"},
    {en:"Run code formatter (via conform.nvim / LSP) on active buffer.",id:"Jalankan formatter pada seluruh buffer aktif."}]
];

export const KEYMAPS = RAW_KEYMAP_DATA.map(([id, cat, mode, keysHtml, rawKeys, action, desc]) => ({
  id, cat, mode, keysHtml, rawKeys, action, desc
}));
